//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsciiPinyin.Web.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AsciiPinyin.Web.Client.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternatives.
        /// </summary>
        public static string Alternatives {
            get {
                return ResourceManager.GetString("Alternatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASCII.
        /// </summary>
        public static string ASCII {
            get {
                return ResourceManager.GetString("ASCII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASCII Pinyin.
        /// </summary>
        public static string ASCIIPinyin {
            get {
                return ResourceManager.GetString("ASCIIPinyin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base character.
        /// </summary>
        public static string BaseCharacter {
            get {
                return ResourceManager.GetString("BaseCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASCII Pinyin of base character.
        /// </summary>
        public static string BaseCharacterASCIIPinyin {
            get {
                return ResourceManager.GetString("BaseCharacterASCIIPinyin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        public static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPA.
        /// </summary>
        public static string IPA {
            get {
                return ResourceManager.GetString("IPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of strokes.
        /// </summary>
        public static string NumberOfStrokes {
            get {
                return ResourceManager.GetString("NumberOfStrokes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinyin.
        /// </summary>
        public static string Pinyin {
            get {
                return ResourceManager.GetString("Pinyin", resourceCulture);
            }
        }
    }
}
