//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsciiPinyin.Web.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AsciiPinyin.Web.Shared.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative character.
        /// </summary>
        public static string AlternativeCharacter {
            get {
                return ResourceManager.GetString("AlternativeCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternatives.
        /// </summary>
        public static string Alternatives {
            get {
                return ResourceManager.GetString("Alternatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base character.
        /// </summary>
        public static string BaseCharacter {
            get {
                return ResourceManager.GetString("BaseCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinyin of base character.
        /// </summary>
        public static string BaseCharacterPinyin {
            get {
                return ResourceManager.GetString("BaseCharacterPinyin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        public static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese character.
        /// </summary>
        public static string ChineseCharacter {
            get {
                return ResourceManager.GetString("ChineseCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compulsory value.
        /// </summary>
        public static string CompulsoryValue {
            get {
                return ResourceManager.GetString("CompulsoryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new alternative.
        /// </summary>
        public static string CreateNewAlternative {
            get {
                return ResourceManager.GetString("CreateNewAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new character.
        /// </summary>
        public static string CreateNewCharacter {
            get {
                return ResourceManager.GetString("CreateNewCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPA.
        /// </summary>
        public static string Ipa {
            get {
                return ResourceManager.GetString("Ipa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a Chinese character.
        /// </summary>
        public static string MustBeChineseCharacter {
            get {
                return ResourceManager.GetString("MustBeChineseCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NewFemale {
            get {
                return ResourceManager.GetString("NewFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NewMale {
            get {
                return ResourceManager.GetString("NewMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of strokes.
        /// </summary>
        public static string NumberOfStrokes {
            get {
                return ResourceManager.GetString("NumberOfStrokes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can contain only basic letters A-Z.
        /// </summary>
        public static string OnlyAsciiAllowed {
            get {
                return ResourceManager.GetString("OnlyAsciiAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can contain only IPA characters.
        /// </summary>
        public static string OnlyIpaAllowed {
            get {
                return ResourceManager.GetString("OnlyIpaAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinyin.
        /// </summary>
        public static string Pinyin {
            get {
                return ResourceManager.GetString("Pinyin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radical.
        /// </summary>
        public static string Radical {
            get {
                return ResourceManager.GetString("Radical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radical alternative.
        /// </summary>
        public static string RadicalAlternative {
            get {
                return ResourceManager.GetString("RadicalAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select base character.
        /// </summary>
        public static string SelectBaseCharacter {
            get {
                return ResourceManager.GetString("SelectBaseCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select radical.
        /// </summary>
        public static string SelectRadical {
            get {
                return ResourceManager.GetString("SelectRadical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select radical alternative.
        /// </summary>
        public static string SelectRadicalAlternative {
            get {
                return ResourceManager.GetString("SelectRadicalAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tone.
        /// </summary>
        public static string Tone {
            get {
                return ResourceManager.GetString("Tone", resourceCulture);
            }
        }
    }
}
